const asteroids = [
    {
      id: 1,
      name: 'Asteroid A',
      price: '$100',
      src: '/test-asteroids/asteroid_fixed_2021AB.svg',
      size: 'Size: 50m',
      hazardLevel: 'Hazard Level: Low',
    },
    {
      id: 2,
      name: 'Asteroid B',
      price: '$150',
      src: '/test-asteroids/asteroid_fixed_3542519.svg',
      size: 'Size: 100m',
      hazardLevel: 'Hazard Level: Medium',
    },
    {
      id: 3,
      name: 'Asteroid C',
      price: '$200',
      src: '/test-asteroids/asteroid_fixed_Asteroid777.svg',
      size: 'Size: 150m',
      hazardLevel: 'Hazard Level: High',
    },
    {
      id: 4,
      name: 'Asteroid D',
      price: '$250',
      src: '/test-asteroids/asteroid_fixed_Comet99.svg',
      size: 'Size: 150m',
      hazardLevel: 'Hazard Level: High',
    },
    {
      id: 5,
      name: 'Asteroid E',
      price: '$300',
      src: '/test-asteroids/asteroid_fixed_Comet99.svg',
      size: 'Size: 300m',
      hazardLevel: 'Hazard Level: Medium',
    },
    {
      id: 6,
      name: 'Asteroid F',
      price: '$350',
      src: '/test-asteroids/asteroid_fixed_XJ42.svg',
      size: 'Size: 500m',
      hazardLevel: 'Hazard Level: Low',
    },{
      id: 7,
      name: 'Asteroid A',
      price: '$100',
      src: '/test-asteroids/asteroid_fixed_2021AB.svg',
      size: 'Size: 50m',
      hazardLevel: 'Hazard Level: Low',
    },
    {
      id: 8,
      name: 'Asteroid B',
      price: '$150',
      src: '/test-asteroids/asteroid_fixed_3542519.svg',
      size: 'Size: 100m',
      hazardLevel: 'Hazard Level: Medium',
    },
    {
      id: 9,
      name: 'Asteroid C',
      price: '$200',
      src: '/test-asteroids/asteroid_fixed_Asteroid777.svg',
      size: 'Size: 150m',
      hazardLevel: 'Hazard Level: High',
    },
    {
      id: 10,
      name: 'Asteroid D',
      price: '$250',
      src: '/test-asteroids/asteroid_fixed_Comet99.svg',
      size: 'Size: 150m',
      hazardLevel: 'Hazard Level: High',
    },
    {
      id: 11,
      name: 'Asteroid E',
      price: '$300',
      src: '/test-asteroids/asteroid_fixed_Comet99.svg',
      size: 'Size: 300m',
      hazardLevel: 'Hazard Level: Medium',
    },
    {
      id: 12,
      name: 'Asteroid F',
      price: '$350',
      src: '/test-asteroids/asteroid_fixed_XJ42.svg',
      size: 'Size: 500m',
      hazardLevel: 'Hazard Level: Low',
    },
  ];

export default asteroids;